spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bay_coffeeshop?createDatabaseIfNotExist=true
    username: root
    password: 123456

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB


